// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.scss";
// import "primeicons/primeicons.css";
// import "primereact/resources/themes/saga-blue/theme.css";
// import "primereact/resources/primereact.min.css";
// import "primereact/resources/themes/lara-light-cyan/theme.css";
// import { useUserContext } from "../app/ui/context/usecontext";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <>
//     <html lang="en">
//        {/* <link id="theme-css" href={"/themes/bootstrap4-light-blue/theme.css"} rel="stylesheet"></link> */}
//       <link
//         rel="stylesheet"
//         href="https://unpkg.com/primeflex@latest/primeflex.css"
//       />
//       <link
//         rel="stylesheet"
//         // href="https://unpkg.com/primereact/resource  s/themes/saga-blue/theme.css"
//       />
//       <link
//         rel="stylesheet"
//         href="https://unpkg.com/primereact/resources/primereact.min.css"
//       />
//       <link
//         rel="stylesheet"
//         href="https://unpkg.com/primeicons/primeicons.css"
//       />
//       <body className={inter.className}>

//        <useUserContext.Provider value={{ textColor, fontFamily, backgroundColor, setTextColor, setFontFamily, setBackgroundColor }}>
//       {children}
//     </useUserContext.Provider>

//         </body>
//      {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/sass.js/0.6.2/sass.min.js" integrity="sha512-lmuNSGprTM9SdDQ8WuvkeGSgUn4R7jogp37VuQ8rrdNOSHQ9UDY9PF5f/gXjhMytuvxf3NADUXL+eb7K0DvIcw=="  ></script>  */}
//     </html>
//     </>
//   );
// }
// 'use client';
import { UserProvider } from '../app/ui/context/usecontext';
import { Inter } from 'next/font/google';
import './globals.scss';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'CRM Dashboard',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://unpkg.com/primeflex@latest/primeflex.css" />
				<link
					rel="stylesheet"
					href="https://unpkg.com/primereact/resources/primereact.min.css"
				/>
				<link rel="stylesheet" href="https://unpkg.com/primeicons/primeicons.css" />
			</head>
			<body className={inter.className}>
				{/* <ThemeProvider theme={theme}> */}
				<UserProvider>{children}</UserProvider>
				{/* </ThemeProvider> */}
			</body>
		</html>
	);
}
